import Footer from "@/components/landing-page/Footer";
import LandingNavbar from "@/components/landing-page/LandingNavbar";
import { SUPPORT_EMAIL } from "@/lib/constants";

const lastUpdated = "8 September 2026";

export default function TermsContent() {
  return (
    <div className="flex min-h-full flex-1 flex-col">
      <LandingNavbar />
      <div className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="text-base-content/60 mt-2 text-sm">Last updated: {lastUpdated}</p>

        <p className="mt-6">
          These terms govern your use of downDATA (&ldquo;the service&rdquo;). By using it, you agree to them. If you don&rsquo;t agree, please don&rsquo;t
          use the service.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">1. The service</h2>
        <p>
          downDATA monitors the status of services you choose to track, such as GitHub, Supabase, Cloudflare, and other Atlassian Statuspage-based
          providers, and shows their live status and incident history. Creating an account lets you save the services you track, group them into boards,
          and connect Slack for notifications. Pricing plans shown on our site describe the tiers we offer; specific billing terms and payment details are
          presented at checkout if and when you subscribe to a paid plan.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">2. Accounts</h2>
        <p>
          Creating an account requires email/password or Google sign-in. You&rsquo;re responsible for keeping your login credentials secure and for
          anything that happens under your account.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">3. Your data</h2>
        <p>
          The services, boards, and Slack connections you configure are yours. We store them only to run your dashboard and send the notifications you
          asked for. We claim no ownership over how you choose to organize or label them.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">4. Plans and billing</h2>
        <p>
          The pricing plans shown on our landing page describe the tiers we offer: monitor limits, check interval, status pages, and history retention. If
          we charge for a plan, the payment processor, billing cycle, and cancellation/refund policy will be disclosed at checkout before you pay, and you
          can cancel a paid plan at any time from your account.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">5. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul className="mt-3 list-disc space-y-1 pl-6">
          <li>Use the service to send spam, harassment, or unlawful content, including via the Slack notification integration.</li>
          <li>Attempt to bypass rate limits, bot protection, or any other technical safeguard.</li>
          <li>Interfere with the service&rsquo;s normal operation or attempt unauthorized access to other users&rsquo; accounts or data.</li>
          <li>Use the service for any unlawful purpose.</li>
        </ul>
        <p className="mt-3">We may suspend or terminate access for violating these terms.</p>

        <h2 className="mt-8 mb-3 text-xl font-bold">6. Third-party status data</h2>
        <p>
          The status and incident data shown for a tracked service is sourced from that service&rsquo;s own public Statuspage API, not generated by us. We
          don&rsquo;t control, and aren&rsquo;t responsible for, its accuracy, availability, or timeliness.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">7. Intellectual property</h2>
        <p>
          The service itself, its design, code, and branding, belongs to us and is protected by applicable intellectual property law. These terms
          don&rsquo;t grant you any rights to it beyond using the service as intended.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">8. Disclaimers</h2>
        <p>
          The service is provided &ldquo;as is&rdquo;, without warranties of any kind. We don&rsquo;t guarantee that monitoring or notifications will be
          uninterrupted, error-free, or catch every incident on a tracked service.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">9. Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, we aren&rsquo;t liable for any indirect, incidental, or consequential damages arising from your use of
          the service, including damages resulting from an outage we failed to detect or notify you about.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">10. Force majeure</h2>
        <p>
          Neither of us is liable for a failure or delay caused by something reasonably outside our control, for example a power or internet outage,
          natural disaster, war, terrorism, labor dispute, or a new law or government action that affects the service.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">11. Termination</h2>
        <p>
          You can stop using the service, or request that your account be deleted, at any time by contacting us at{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="link">
            {SUPPORT_EMAIL}
          </a>
          . We may suspend or terminate accounts that violate these terms.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">12. Governing law and legal entity</h2>
        <p>
          This service is operated by <strong>[Insert your legal entity name here]</strong>, based at{" "}
          <strong>[Insert your registered business address here]</strong>. These terms are governed by the laws of Slovakia, without regard to its
          conflict-of-law principles.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">13. Changes to these terms</h2>
        <p>If we make material changes to these terms, we&rsquo;ll update the &ldquo;Last updated&rdquo; date above.</p>

        <h2 className="mt-8 mb-3 text-xl font-bold">14. Severability</h2>
        <p>If any part of these terms is found unenforceable or invalid, that part will be removed and the rest of these terms will remain in full effect.</p>

        <h2 className="mt-8 mb-3 text-xl font-bold">15. Entire agreement</h2>
        <p>
          These terms, together with anything they expressly refer to (like our Privacy Policy), make up the entire agreement between you and us about the
          service, and replace any earlier agreement or understanding about it.
        </p>

        <h2 className="mt-8 mb-3 text-xl font-bold">16. Contact</h2>
        <p>
          Questions about these terms? Email us at{" "}
          <a href={`mailto:${SUPPORT_EMAIL}`} className="link">
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </div>
      <Footer />
    </div>
  );
}
