.PHONY: run dev build

## run: run the cmd/api application
run:
	go run ./cmd/api

## dev: run the application with live reload via air
dev:
	air

## build: build the cmd/api application
build:
	go build -o ./bin/api ./cmd/api
